In [1]:
import numpy as np

w = np.array([
    [0.1, 0.4],
    [0.8, 0.6]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.00265], [-0.00817]])
output = np.array([[0.35], [0.9]])
activation[1](output) * (w @ grad_output)

array([[-0.00080376],
       [-0.00063198]])

In [2]:
w = np.array([
    [0.3],
    [0.9]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.0407]])
output = np.array([[0.680], [0.664]])
activation[1](output) * (w @ grad_output)

array([[-0.0026569],
       [-0.0081723]])

In [4]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
import numpy as np


layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'sigmoid', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



[[0.69028349]]
[[0.68205434]]
[[0.67401164]]
[[0.66617304]]
[[0.65855334]]
[[0.65116451]]
[[0.64401584]]
[[0.63711406]]
[[0.63046358]]
[[0.62406667]]
[[0.6179237]]
[[0.61203339]]
[[0.60639301]]
[[0.60099861]]
[[0.59584523]]
[[0.59092708]]
[[0.58623767]]
[[0.58177006]]
[[0.57751687]]
[[0.57347051]]
[[0.56962319]]
[[0.56596707]]
[[0.5624943]]
[[0.55919708]]
[[0.55606772]]
[[0.55309866]]
[[0.55028256]]
[[0.54761223]]
[[0.54508073]]
[[0.54268134]]
[[0.5404076]]
[[0.53825328]]
[[0.5362124]]
[[0.53427923]]
[[0.53244831]]
[[0.53071439]]
[[0.52907247]]
[[0.52751781]]
[[0.52604585]]
[[0.52465228]]
[[0.523333]]
[[0.5220841]]
[[0.52090187]]
[[0.51978279]]
[[0.51872352]]
[[0.51772088]]
[[0.51677188]]
[[0.51587365]]
[[0.51502349]]
[[0.51421884]]
[[0.51345728]]
[[0.5127365]]
[[0.51205432]]
[[0.51140869]]
[[0.51079764]]
[[0.51021932]]
[[0.50967199]]
[[0.50915398]]
[[0.50866372]]
[[0.50819974]]
[[0.50776061]]
[[0.50734501]]
[[0.50695167]]
[[0.50657941]]
[[0.5062271]]
[[0.50589365]]
[[0.50557808]]
[[0.

In [1]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
import numpy as np

adam = Adam()
layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer2.compile(optimizer=adam)
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'sigmoid', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



[[0.69028349]]
[[0.68707769]]
[[0.68387261]]
[[0.68066925]]
[[0.67746863]]
[[0.67427179]]
[[0.67107976]]
[[0.66789361]]
[[0.66471442]]
[[0.66154325]]
[[0.6583812]]
[[0.65522936]]
[[0.65208884]]
[[0.64896074]]
[[0.64584618]]
[[0.64274627]]
[[0.63966211]]
[[0.63659482]]
[[0.63354551]]
[[0.63051527]]
[[0.6275052]]
[[0.62451639]]
[[0.62154992]]
[[0.61860686]]
[[0.61568826]]
[[0.61279516]]
[[0.60992859]]
[[0.60708957]]
[[0.60427907]]
[[0.60149808]]
[[0.59874754]]
[[0.59602838]]
[[0.59334152]]
[[0.59068781]]
[[0.58806813]]
[[0.58548329]]
[[0.58293409]]
[[0.58042129]]
[[0.57794563]]
[[0.57550781]]
[[0.57310849]]
[[0.57074831]]
[[0.56842787]]
[[0.56614771]]
[[0.56390836]]
[[0.56171031]]
[[0.55955398]]
[[0.5574398]]
[[0.5553681]]
[[0.55333922]]
[[0.55135343]]
[[0.54941097]]
[[0.54751202]]
[[0.54565673]]
[[0.54384521]]
[[0.54207752]]
[[0.54035368]]
[[0.53867367]]
[[0.53703742]]
[[0.53544482]]
[[0.53389573]]
[[0.53238996]]
[[0.53092727]]
[[0.5295074]]
[[0.52813005]]
[[0.52679487]]
[[0.52550147]]


In [2]:

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
from model.layers.flatten import Flatten
from model.layers.dense import Dense
import numpy as np

adam = Adam()
input = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 46, 47, 48, 49],
    [50, 51, 52, 53, 54]]
])


convLayer = Conv2D(input_shape=(2,5,5), output_shape=(2,3,3), filters=2, kernel_size=3)
flattenLayer = Flatten(input_shape=(2,3,3), output_shape=(18,1), activation='sigmoid')
flattenLayer.forward(convLayer.forward(input))

layer2 = Dense(input_shape=(18,1), output_shape=(5,1))
layer3 = Dense(input_shape=(5,1), output_shape=(1,1))

layer2.compile(optimizer='adam')
layer3.compile(optimizer='adam')
output = Output((1,1), (1,1), np.array([[0.50]]), 'sigmoid', '')

for i in range(1000):
     final_out = output.forward(layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input)))))
     print(final_out)
     layer2.backward(layer3.backward(output.backward(final_out)))

#layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input))))





[[0.47662581]]
[[0.48286545]]
[[0.48898864]]
[[0.49483477]]
[[0.5001577]]
[[0.50463959]]
[[0.50798198]]
[[0.51003803]]
[[0.51085944]]
[[0.51062826]]
[[0.50956887]]
[[0.50790078]]
[[0.50582655]]
[[0.50353463]]
[[0.50120395]]
[[0.49900383]]
[[0.49708709]]
[[0.49557755]]
[[0.49455732]]
[[0.49406]]
[[0.49407236]]
[[0.49454261]]
[[0.49539079]]
[[0.49651837]]
[[0.49781601]]
[[0.49917032]]
[[0.50047073]]
[[0.50161704]]
[[0.50252726]]
[[0.50314439]]
[[0.50344045]]
[[0.50341715]]
[[0.50310323]]
[[0.50254964]]
[[0.50182352]]
[[0.5010017]]
[[0.500164]]
[[0.49938641]]
[[0.49873466]]
[[0.49825862]]
[[0.49798838]]
[[0.49793253]]
[[0.49807877]]
[[0.49839654]]
[[0.49884122]]
[[0.49935927]]
[[0.49989387]]
[[0.50039059]]
[[0.5008026]]
[[0.50109502]]
[[0.50124771]]
[[0.50125649]]
[[0.50113243]]
[[0.5008997]]
[[0.5005921]]
[[0.50024884]]
[[0.49991003]]
[[0.49961229]]
[[0.49938496]]
[[0.49924737]]
[[0.49920735]]
[[0.49926111]]
[[0.49939453]]
[[0.49958549]]
[[0.49980698]]
[[0.50003055]]
[[0.50022971]]
[[0.5

In [25]:
a = np.array([[1,1,1,1,1]]).T
b = np.array([[2,2,2]]).T
a * b

ValueError: operands could not be broadcast together with shapes (5,1) (3,1) 

In [10]:
input = np.array([[1,2,3,4]]).T
grad_output = np.array([[5,6]])
print(input*grad_output)


[[ 5  6]
 [10 12]
 [15 18]
 [20 24]]


In [ ]:
grad_outputs = np.array([
    [1,2],
    [3,4]
])