In [2]:
import numpy as np

w = np.array([
    [0.1, 0.4],
    [0.8, 0.6]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.00265], [-0.00817]])
output = np.array([[0.35], [0.9]])
activation[1](output) * (w @ grad_output)

array([[-0.00080376],
       [-0.00063198]])

In [3]:
w = np.array([
    [0.3],
    [0.9]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.0407]])
output = np.array([[0.680], [0.664]])
activation[1](output) * (w @ grad_output)

array([[-0.0026569],
       [-0.0081723]])

In [4]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
import numpy as np


layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'relu', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



KeyError: 2

## Train a model that is only fully connected layers:

In [ ]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
import numpy as np

adam = Adam()
layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer2.compile(optimizer=adam)
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'relu', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



[[0.69028349]]
[[0.68707769]]
[[0.68387261]]
[[0.68066925]]
[[0.67746863]]
[[0.67427179]]
[[0.67107976]]
[[0.66789361]]
[[0.66471442]]
[[0.66154325]]
[[0.6583812]]
[[0.65522936]]
[[0.65208884]]
[[0.64896074]]
[[0.64584618]]
[[0.64274627]]
[[0.63966211]]
[[0.63659482]]
[[0.63354551]]
[[0.63051527]]
[[0.6275052]]
[[0.62451639]]
[[0.62154992]]
[[0.61860686]]
[[0.61568826]]
[[0.61279516]]
[[0.60992859]]
[[0.60708957]]
[[0.60427907]]
[[0.60149808]]
[[0.59874754]]
[[0.59602838]]
[[0.59334152]]
[[0.59068781]]
[[0.58806813]]
[[0.58548329]]
[[0.58293409]]
[[0.58042129]]
[[0.57794563]]
[[0.57550781]]
[[0.57310849]]
[[0.57074831]]
[[0.56842787]]
[[0.56614771]]
[[0.56390836]]
[[0.56171031]]
[[0.55955398]]
[[0.5574398]]
[[0.5553681]]
[[0.55333922]]
[[0.55135343]]
[[0.54941097]]
[[0.54751202]]
[[0.54565673]]
[[0.54384521]]
[[0.54207752]]
[[0.54035368]]
[[0.53867367]]
[[0.53703742]]
[[0.53544482]]
[[0.53389573]]
[[0.53238996]]
[[0.53092727]]
[[0.5295074]]
[[0.52813005]]
[[0.52679487]]
[[0.52550147]]


## Train a model that has convolutional layers and fully connected layers
### but only do backprop on the fully connected layers

In [ ]:

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
from model.layers.flatten import Flatten
from model.layers.dense import Dense
import numpy as np

adam = Adam()
input = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 46, 47, 48, 49],
    [50, 51, 52, 53, 54]]
])


convLayer = Conv2D(input_shape=(2,5,5), input.shape=(2,3,3), filters=2, kernel_size=3)
flattenLayer = Flatten(input_shape=(2,3,3), input.shape=(18,1), activation='relu')
flattenLayer.forward(convLayer.forward(input))

layer2 = Dense(input_shape=(18,1), input.shape=(5,1))
layer3 = Dense(input_shape=(5,1), input.shape=(1,1))

layer2.compile(optimizer='adam')
layer3.compile(optimizer='adam')
output = Output((1,1), (1,1), np.array([[0.50]]), 'relu', '')

for i in range(1000):
     final_out = output.forward(layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input)))))
     print(final_out)
     # train fully-connected portion
     #layer2.backward(layer3.backward(output.backward(final_out)))
     
     # train convolutional portion:
     

#layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input))))





[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.577077

## train a network that has convolutional layers:

In [2]:

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
from model.layers.dropout import ConvDropout, DenseDropout
import numpy as np
import tqdm

input = np.random.uniform(low=-1, high=1, size=(2,12,12))
# make convolutional layers
convLayer1 = Conv2D(input_shape=(2,12,12), output_shape=(4,10,10), filters=4, kernel_size=3, activation='relu')
convLayer1.compile(optimizer='adam')

convDropoutLayer = ConvDropout(input_shape=(4,10,10), output_shape=(4,10,10), dropout_rate=0.5)

convLayer2 = Conv2D(input_shape=(4,10,10), output_shape=(10,7,7), filters=10, kernel_size=4, activation='relu')
convLayer2.compile(optimizer='adam')

poolingLayer = MaxPool2D(input_shape=(10,7,7), output_shape=(10,3,3), pool_size=(5,5))

convLayer3 = Conv2D(input_shape=(10,3,3), output_shape=(1,3,3), filters=1, kernel_size=1, activation='relu')
convLayer3.compile(optimizer='adam')

# make flatten layer
flattenLayer = Flatten(input_shape=(1,3,3), output_shape=(9,1), activation='relu')

# make fully connected layers
layer2 = Dense(input_shape=(9,1), output_shape=(5,1), activation='relu')
layer2.compile(optimizer='adam')

denseDropoutLayer = DenseDropout(input_shape=(5,1), output_shape=(5,1), dropout_rate=0.5)

layer3 = Dense(input_shape=(5,1), output_shape=(1,1), activation='relu')
layer3.compile(optimizer='adam')

# make output
output = Output((1,1), (1,1), np.array([[0.24]]), 'sigmoid', '')

iters = 2000
for i in range(iters):
     conv_out = convLayer3.forward(poolingLayer.forward(convLayer2.forward(convDropoutLayer.forward(convLayer1.forward(input)))))
     final_out = output.forward(layer3.forward(denseDropoutLayer.forward(layer2.forward(flattenLayer.forward(conv_out)))))
     print(final_out)
     # train fully-connected portion
     fully_connected_backprop = layer2.backward(denseDropoutLayer.backward(layer3.backward(output.backward(final_out))))
     # train convolutional portion:
     convLayer1.backward(convDropoutLayer.backward(convLayer2.backward(poolingLayer.backward(convLayer3.backward(flattenLayer.backward(fully_connected_backprop))))))


[[0.50261229]]
[[0.5023452]]
[[0.50207809]]
[[0.5017912]]
[[0.50154698]]
[[0.50127819]]
[[0.5010285]]
[[0.50076478]]
[[0.50051046]]
[[0.50026073]]
[[0.50000511]]
[[0.49975446]]
[[0.49950309]]
[[0.4992524]]
[[0.49900218]]
[[0.49875242]]
[[0.4985029]]
[[0.49825344]]
[[0.49800404]]
[[0.4977547]]
[[0.49750543]]
[[0.49725623]]
[[0.4970071]]
[[0.49675804]]
[[0.49650906]]
[[0.49626016]]
[[0.49601133]]
[[0.49576259]]
[[0.49551393]]
[[0.49526536]]
[[0.49501688]]
[[0.49476848]]
[[0.49452018]]
[[0.49427196]]
[[0.49402384]]
[[0.49377582]]
[[0.49352788]]
[[0.49328005]]
[[0.49303231]]
[[0.49278467]]
[[0.49253713]]
[[0.49228968]]
[[0.49204234]]
[[0.4917951]]
[[0.49154796]]
[[0.49130093]]
[[0.49105399]]
[[0.49080716]]
[[0.49056043]]
[[0.49031381]]
[[0.49006729]]
[[0.48982088]]
[[0.48957457]]
[[0.48932836]]
[[0.48908226]]
[[0.48883627]]
[[0.48859038]]
[[0.4883446]]
[[0.48809893]]
[[0.48785336]]
[[0.48760789]]
[[0.48736253]]
[[0.48711728]]
[[0.48687214]]
[[0.4866271]]
[[0.48638217]]
[[0.48613734]]
[[0.4

## multiple channel example of maxpooling backprop

In [1]:
input = np.array([[
    [111,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 4, 44, 488, 49],
    [50, 51, 52, 53, 54]]
])

pool_size = (3,3)
stride = 1
output_size = int((input.shape[1] - pool_size[0])/stride) + 1
output = np.zeros((input.shape[0], output_size, output_size))
positions = np.zeros(output.shape, dtype=(int, 3))
for i in range(output_size): # rows
    for j in range(output_size): # columns
        row_start = i*stride
        row_end = row_start + pool_size[0]
        col_start = j*stride
        col_end = col_start + pool_size[1]
        for k in range(input.shape[0]): # channels
            frame = input[k,row_start:row_end, col_start:col_end]
            output[k,i,j] = np.max(frame)
            # get the spot in the frame with the max value
            positions[k,i,j,1:] = np.unravel_index(np.argmax(frame), frame.shape)
            # add channel to position
            positions[k,i,j,0] = k
            # add offsets to get the spot in the output matrix with max value of this frame
            positions[k,i,j,1] += row_start
            positions[k,i,j,2] += col_start
            
output_grads = np.array(
    [
        [
            [1, 2, 3],
            [4,5,6],
            [7,8,9]
        ],

        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    ]
)
r_val = np.zeros(input.shape)
channel_pos = positions[:, :, :, 0]
row_pos = positions[:, :, :, 1]
col_pos = positions[:, :, :, 2]
r_val[channel_pos, row_pos, col_pos] = output_grads
print(input)
print(output)
print(r_val)


NameError: name 'np' is not defined

## Multiple channel example of dropout

In [14]:
input = np.array([[
    [111,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 4, 44, 488, 49],
    [50, 51, 52, 53, 54]]
])
input_shape = input.shape
dropout_rate = 0.5

dropout_num = int(input_shape[0] * input_shape[1] * input_shape[2] * dropout_rate)
z_coord = np.random.randint(low=0, high=input.shape[0], size=dropout_num)
x_coord = np.random.randint(low=0, high=input_shape[1], size=dropout_num)
y_coord = np.random.randint(low=0, high=input_shape[2], size=dropout_num)
positions = np.stack((z_coord, x_coord, y_coord))
print(positions)
input_copy = np.copy(input)
input_copy[z_coord,x_coord,y_coord] = 0.0
print(input_copy)


output_grads = input
# this is a matrix of the channel coordinates for each of the max values that we outputed upon forward prop
channel_pos = positions[0]
# and a matrix for the row coordinates
row_pos = positions[1]
# and a matrix for the col coordinates
col_pos = positions[2]
output_grads[channel_pos, row_pos, col_pos] = 0.0
output_grads


[[0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1]
 [1 1 0 3 1 4 1 1 0 0 4 4 0 2 1 4 0 0 0 1 2 1 0 0 4]
 [2 3 1 0 0 4 0 2 0 0 3 2 1 3 0 3 3 0 1 0 4 4 3 4 1]]
[[[  0   0   3   0   0]
  [  0   7   0   0  10]
  [ 11  12  13   0  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24   0]]

 [[  0   0  32   0  34]
  [  0  36   0  38   0]
  [ 40  41  42  43   0]
  [  0   4  44 488  49]
  [ 50   0   0   0  54]]]


array([[[  0,   0,   3,   0,   0],
        [  0,   7,   0,   0,  10],
        [ 11,  12,  13,   0,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,   0]],

       [[  0,   0,  32,   0,  34],
        [  0,  36,   0,  38,   0],
        [ 40,  41,  42,  43,   0],
        [  0,   4,  44, 488,  49],
        [ 50,   0,   0,   0,  54]]])

## Sequential test


In [2]:
from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
from model.layers.dropout import ConvDropout, DenseDropout
import numpy as np
from sequenal import Sequential


from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
from model.layers.dropout import ConvDropout, DenseDropout
import numpy as np


input = np.random.uniform(low=-1, high=1, size=(2,12,12))
# make convolutional layers
convLayer1 = Conv2D(input_shape=(2,12,12), output_shape=(4,10,10), filters=4, kernel_size=3, activation='relu')
convDropoutLayer = ConvDropout(input_shape=(4,10,10), output_shape=(4,10,10), dropout_rate=0.5)
convLayer2 = Conv2D(input_shape=(4,10,10), output_shape=(10,7,7), filters=10, kernel_size=4, activation='relu')
poolingLayer = MaxPool2D(input_shape=(10,7,7), output_shape=(10,3,3), pool_size=(5,5))
convLayer3 = Conv2D(input_shape=(10,3,3), output_shape=(1,3,3), filters=1, kernel_size=1, activation='relu')

# make flatten layer
flattenLayer = Flatten(input_shape=(1,3,3), output_shape=(9,1), activation='relu')
layer2 = Dense(input_shape=(9,1), output_shape=(5,1), activation='relu')
denseDropoutLayer = DenseDropout(input_shape=(5,1), output_shape=(5,1), dropout_rate=0.5)
layer3 = Dense(input_shape=(5,1), output_shape=(1,1), activation='relu')
# make output
output = Output((1,1), (1,1), np.array([[0.24]]), 'sigmoid', '')
input = np.random.uniform(low=-1, high=1, size=(2,12,12))
sequential = Sequential()


sequential.add(convLayer1)
sequential.add(convLayer2)
sequential.add(poolingLayer)
sequential.add(convLayer3)
sequential.add(flattenLayer)
sequential.add(layer2)
sequential.add(layer3)
sequential.add(output)

sequential.compile('adam')


for i in range(150):
    final_out =sequential.forward(input)
    print(final_out)
    sequential.backward(final_out)

[[0.50264213]]
[[0.50236389]]
[[0.50208917]]
[[0.50181788]]
[[0.50154991]]
[[0.50128512]]
[[0.50102334]]
[[0.50076437]]
[[0.50050794]]
[[0.50025379]]
[[0.50000161]]
[[0.49975104]]
[[0.49950131]]
[[0.49925164]]
[[0.49900202]]
[[0.49875244]]
[[0.49850293]]
[[0.49825347]]
[[0.49800407]]
[[0.49775474]]
[[0.49750547]]
[[0.49725627]]
[[0.49700714]]
[[0.49675808]]
[[0.49650911]]
[[0.4962602]]
[[0.49601138]]
[[0.49576264]]
[[0.49551399]]
[[0.49526542]]
[[0.49501694]]
[[0.49476854]]
[[0.49452024]]
[[0.49427203]]
[[0.49402391]]
[[0.49377588]]
[[0.49352795]]
[[0.49328012]]
[[0.49303238]]
[[0.49278474]]
[[0.4925372]]
[[0.49228976]]
[[0.49204242]]
[[0.49179518]]
[[0.49154804]]
[[0.49130101]]
[[0.49105407]]
[[0.49080724]]
[[0.49056052]]
[[0.49031389]]
[[0.49006738]]
[[0.48982096]]
[[0.48957465]]
[[0.48932845]]
[[0.48908235]]
[[0.48883636]]
[[0.48859047]]
[[0.48834469]]
[[0.48809902]]
[[0.48785345]]
[[0.48760799]]
[[0.48736263]]
[[0.48711738]]
[[0.48687223]]
[[0.4866272]]
[[0.48638226]]
[[0.48613744]