## train a network that has convolutional layers & dense:
We choose a floating point number as the ouput and create a cnn for that output  and it works.

### 


In [6]:
from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
from model.layers.dropout import ConvDropout, DenseDropout
import numpy as np


input = np.random.uniform(low=-1, high=1, size=(2,12,12))
# make convolutional layers
convLayer1 = Conv2D(input_shape=(2,12,12), output_shape=(4,10,10), filters=4, kernel_size=3, activation='relu')
convLayer1.compile(optimizer='adam')

convDropoutLayer = ConvDropout(input_shape=(4,10,10), output_shape=(4,10,10), dropout_rate=0.5)

convLayer2 = Conv2D(input_shape=(4,10,10), output_shape=(10,7,7), filters=10, kernel_size=4, activation='relu')
convLayer2.compile(optimizer='adam')

poolingLayer = MaxPool2D(input_shape=(10,7,7), output_shape=(10,3,3), pool_size=(5,5))

convLayer3 = Conv2D(input_shape=(10,3,3), output_shape=(1,3,3), filters=1, kernel_size=1, activation='relu')
convLayer3.compile(optimizer='adam')

# make flatten layer
flattenLayer = Flatten(input_shape=(1,3,3), output_shape=(9,1))

# make fully connected layers
layer2 = Dense(input_shape=(9,1), output_shape=(5,1), activation='relu')
layer2.compile(optimizer='adam')

denseDropoutLayer = DenseDropout(input_shape=(5,1), output_shape=(5,1), dropout_rate=0.5)

layer3 = Dense(input_shape=(5,1), output_shape=(1,1), activation='relu')
layer3.compile(optimizer='adam')

# make output
output = Output((1,1), (1,1), np.array([[0.24]]), 'sigmoid')

iters = 2000
for i in range(iters):
     conv_out = convLayer3.forward(poolingLayer.forward(convLayer2.forward(convDropoutLayer.forward(convLayer1.forward(input)))))
     final_out = output.forward(layer3.forward(denseDropoutLayer.forward(layer2.forward(flattenLayer.forward(conv_out)))))
     print(final_out)
     # train fully-connected portion
     fully_connected_backprop = layer2.backward(denseDropoutLayer.backward(layer3.backward(output.backward(final_out))))
     # train convolutional portion:
     convLayer1.backward(convDropoutLayer.backward(convLayer2.backward(poolingLayer.backward(convLayer3.backward(flattenLayer.backward(fully_connected_backprop))))))


[[0.00740241]]
[[1.02947486e-09]]
[[0.01782432]]
[[2.45732736e-05]]
[[0.01799948]]
[[0.29022819]]
[[0.01222888]]
[[1.10359248e-05]]
[[0.01671151]]
[[0.50949953]]
[[0.10234483]]
[[0.00014261]]
[[0.24685545]]
[[0.00139533]]
[[0.26414054]]
[[0.03094517]]
[[0.10327393]]
[[0.00025282]]
[[0.42220047]]
[[0.00639348]]
[[0.50281442]]
[[0.48908514]]
[[0.50252658]]
[[0.48085884]]
[[0.01703366]]
[[0.05340069]]
[[0.25084297]]
[[0.00088123]]
[[0.5014899]]
[[0.14196869]]
[[0.29853822]]
[[0.29028049]]
[[0.00023684]]
[[0.04430394]]
[[0.49757509]]
[[0.4984192]]
[[0.50035153]]
[[0.31273563]]
[[0.49688352]]
[[0.09986146]]
[[0.27399553]]
[[0.37855526]]
[[0.01349571]]
[[0.49905747]]
[[0.49579339]]
[[0.49470854]]
[[0.49453456]]
[[0.34843456]]
[[0.26567678]]
[[0.4931193]]
[[0.35053361]]
[[0.46225606]]
[[0.49217289]]
[[0.4368483]]
[[0.50246607]]
[[0.41428967]]
[[0.07745019]]
[[0.27219112]]
[[0.48640164]]
[[0.49534671]]
[[0.20407449]]
[[0.43312587]]
[[0.48568083]]
[[0.48785394]]
[[0.39732856]]
[[0.4949022]]
[[0

## test sub_data set(4 types)

### 
we have a 4-type dataset(star,circle,square,triangle). We create a cnn for that datasets. And when we do the testing the model that we saved, the accurancy is only 25.7%, which means that it not really works.

In [1]:
from sequential import Sequential

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
from model.layers.dropout import ConvDropout, DenseDropout
import numpy as np

path = '.\shapes\small'
sequential = Sequential()
map_dictionary={
    'star':np.array([[1],[0],[0],[0]]),
    'circle':np.array([[0],[1],[0],[0]]),
    'square':np.array([[0],[0],[1],[0]]),
    'triangle': np.array([[0],[0],[0],[1]])
}
train_value,train_target, validation_value , validation_target,indices =sequential.preprocess_dataset(path,map_dictionary)
#print(train_target[0])



input = train_value[0]   #np.random.uniform(low=-1, high=1, size=(2,12,12))
# make convolutional layers

convLayer1 = Conv2D(input_shape=(3,20,20), output_shape=(4,17,17), filters=4, kernel_size=4, activation='relu')
convDropoutLayer = ConvDropout(input_shape=(4,17,17), output_shape=(4,17,17), dropout_rate=0.2)
convLayer2 = Conv2D(input_shape=(4,17,17), output_shape=(2,13,13), filters=2, kernel_size=5, activation='sigmoid')
poolingLayer = MaxPool2D(input_shape=(2,13,13), output_shape=(2,8,8), pool_size=(6,6))
convLayer3 = Conv2D(input_shape=(2,8,8), output_shape=(1,4,4), filters=1, kernel_size=5, activation='sigmoid')



#make flatten layer
flattenLayer = Flatten(input_shape=(1,4,4), output_shape=(16,1))
layer2 = Dense(input_shape=(16,1), output_shape=(8,1), activation='sigmoid')
denseDropoutLayer = DenseDropout(input_shape=(8,1), output_shape=(8,1), dropout_rate=0.2)
layer3 = Dense(input_shape=(8,1), output_shape=(4,1), activation='sigmoid')
output = Output((4,1), (4,1), train_target[0], 'sigmoid')



sequential = Sequential()
sequential.add(convLayer1)
sequential.add(convLayer2)
sequential.add(poolingLayer)
sequential.add(convLayer3)
sequential.add(flattenLayer)
sequential.add(layer2)
sequential.add(layer3)
sequential.add(output)
sequential.compile('adam')



sequential.training(train_value=train_value,train_target=train_target,indices=indices,number_of_iteration=1)
sequential.save('alexbot.hd5')



[[0.29184938]
 [0.41746726]
 [0.69793681]
 [0.46581301]]
[[0.29387739]
 [0.42144201]
 [0.6981674 ]
 [0.46302932]]
[[0.29453495]
 [0.41821103]
 [0.69622757]
 [0.46373897]]
[[0.29682169]
 [0.42397451]
 [0.69790713]
 [0.46292833]]
[[0.29307835]
 [0.41460364]
 [0.69187483]
 [0.46233786]]
[[0.29365685]
 [0.41420737]
 [0.69248442]
 [0.46195946]]
[[0.29469517]
 [0.41693625]
 [0.6918909 ]
 [0.45943535]]
[[0.29329759]
 [0.41648066]
 [0.6891594 ]
 [0.45854414]]
[[0.29346058]
 [0.41242627]
 [0.68795051]
 [0.45949547]]
[[0.29261294]
 [0.41311024]
 [0.68669802]
 [0.45906574]]
[[0.29160444]
 [0.41028609]
 [0.68523129]
 [0.45808701]]
[[0.29127726]
 [0.40957083]
 [0.68429466]
 [0.45705188]]
[[0.29141753]
 [0.4092099 ]
 [0.68314172]
 [0.45551007]]
[[0.29121644]
 [0.40712725]
 [0.68153467]
 [0.45500481]]
[[0.29148365]
 [0.40807098]
 [0.68135117]
 [0.45359559]]
[[0.29408633]
 [0.41102841]
 [0.68224725]
 [0.45197497]]
[[0.29164009]
 [0.40425713]
 [0.67881287]
 [0.45246147]]
[[0.2905274 ]
 [0.40374825]
 [0

: 

In [1]:
from sequential import Sequential
model =Sequential.load('alexbot.hd5')
print(model.layers)

[<model.layers.conv2d.Conv2D object at 0x0000026E7FD5CC50>, <model.layers.conv2d.Conv2D object at 0x0000026E7FD6F4D0>, <model.layers.maxpool2d.MaxPool2D object at 0x0000026E7FD54C10>, <model.layers.conv2d.Conv2D object at 0x0000026E7FD1FD10>, <model.layers.flatten.Flatten object at 0x0000026E7FD1F050>, <model.layers.dense.Dense object at 0x0000026E7FD1DED0>, <model.layers.dense.Dense object at 0x0000026E7FACCB10>, <model.layers.output.Output object at 0x0000026E07005ED0>]


In [2]:
import numpy as np
def test(model,test_data,test_target):
    number_of_test =len(test_data)
    correct=0
    for i,data in enumerate(test_data):
        output =model.forward(data, index=0)
        if np.argmax(output)== np.argmax(test_target[i]):
            correct = correct+1
    return correct/number_of_test

path = '.\shapes\small'
sequential = Sequential()
map_dictionary={
    'star':np.array([[1],[0],[0],[0]]),
    'circle':np.array([[0],[1],[0],[0]]),
    'square':np.array([[0],[0],[1],[0]]),
    'triangle': np.array([[0],[0],[0],[1]])
}
train_value,train_target, validation_value , validation_target,indices =model.preprocess_dataset(path,map_dictionary)
rate =test(model,validation_value,validation_target)
print(rate)



0.2575150300601202
