In [2]:
import numpy as np

w = np.array([
    [0.1, 0.4],
    [0.8, 0.6]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.00265], [-0.00817]])
output = np.array([[0.35], [0.9]])
activation[1](output) * (w @ grad_output)

array([[-0.00080376],
       [-0.00063198]])

In [3]:
w = np.array([
    [0.3],
    [0.9]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.0407]])
output = np.array([[0.680], [0.664]])
activation[1](output) * (w @ grad_output)

array([[-0.0026569],
       [-0.0081723]])

In [4]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
import numpy as np


layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'relu', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



KeyError: 2

## Train a model that is only fully connected layers:

In [ ]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
import numpy as np

adam = Adam()
layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer2.compile(optimizer=adam)
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'relu', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(100):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



[[0.69028349]]
[[0.68707769]]
[[0.68387261]]
[[0.68066925]]
[[0.67746863]]
[[0.67427179]]
[[0.67107976]]
[[0.66789361]]
[[0.66471442]]
[[0.66154325]]
[[0.6583812]]
[[0.65522936]]
[[0.65208884]]
[[0.64896074]]
[[0.64584618]]
[[0.64274627]]
[[0.63966211]]
[[0.63659482]]
[[0.63354551]]
[[0.63051527]]
[[0.6275052]]
[[0.62451639]]
[[0.62154992]]
[[0.61860686]]
[[0.61568826]]
[[0.61279516]]
[[0.60992859]]
[[0.60708957]]
[[0.60427907]]
[[0.60149808]]
[[0.59874754]]
[[0.59602838]]
[[0.59334152]]
[[0.59068781]]
[[0.58806813]]
[[0.58548329]]
[[0.58293409]]
[[0.58042129]]
[[0.57794563]]
[[0.57550781]]
[[0.57310849]]
[[0.57074831]]
[[0.56842787]]
[[0.56614771]]
[[0.56390836]]
[[0.56171031]]
[[0.55955398]]
[[0.5574398]]
[[0.5553681]]
[[0.55333922]]
[[0.55135343]]
[[0.54941097]]
[[0.54751202]]
[[0.54565673]]
[[0.54384521]]
[[0.54207752]]
[[0.54035368]]
[[0.53867367]]
[[0.53703742]]
[[0.53544482]]
[[0.53389573]]
[[0.53238996]]
[[0.53092727]]
[[0.5295074]]
[[0.52813005]]
[[0.52679487]]
[[0.52550147]]


## Train a model that has convolutional layers and fully connected layers
### but only do backprop on the fully connected layers

In [ ]:

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
from model.layers.flatten import Flatten
from model.layers.dense import Dense
import numpy as np

adam = Adam()
input = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 46, 47, 48, 49],
    [50, 51, 52, 53, 54]]
])


convLayer = Conv2D(input_shape=(2,5,5), output_shape=(2,3,3), filters=2, kernel_size=3)
flattenLayer = Flatten(input_shape=(2,3,3), output_shape=(18,1), activation='relu')
flattenLayer.forward(convLayer.forward(input))

layer2 = Dense(input_shape=(18,1), output_shape=(5,1))
layer3 = Dense(input_shape=(5,1), output_shape=(1,1))

layer2.compile(optimizer='adam')
layer3.compile(optimizer='adam')
output = Output((1,1), (1,1), np.array([[0.50]]), 'relu', '')

for i in range(1000):
     final_out = output.forward(layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input)))))
     print(final_out)
     # train fully-connected portion
     #layer2.backward(layer3.backward(output.backward(final_out)))
     
     # train convolutional portion:
     

#layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input))))





[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.57707703]]
[[0.577077

## train a network that is only convolutional layers:

In [1]:

from model.layers.conv2d import Conv2D
from model.layers.output import Output
from model.layers.input import Input
from model.optimizers.adam import Adam
from model.layers.flatten import Flatten
from model.layers.dense import Dense
from model.layers.maxpool2d import MaxPool2D
import numpy as np

input = np.random.uniform(low=-1, high=1, size=(2,12,12))
# make convolutional layers
convLayer1 = Conv2D(input_shape=(2,12,12), output_shape=(4,10,10), filters=4, kernel_size=3, activation='relu')
convLayer1.compile(optimizer='adam')
convLayer2 = Conv2D(input_shape=(4,10,10), output_shape=(10,7,7), filters=10, kernel_size=4, activation='relu')
convLayer2.compile(optimizer='adam')

poolingLayer = MaxPool2D(input_shape=(10,7,7), output_shape=(10,3,3), pool_size=(5,5))

convLayer3 = Conv2D(input_shape=(10,3,3), output_shape=(1,3,3), filters=1, kernel_size=1, activation='relu')
convLayer3.compile(optimizer='adam')

# make flatten layer
flattenLayer = Flatten(input_shape=(1,3,3), output_shape=(9,1), activation='relu')

# make fully connected layers
layer2 = Dense(input_shape=(9,1), output_shape=(5,1), activation='relu')
layer2.compile(optimizer='adam')
layer3 = Dense(input_shape=(5,1), output_shape=(1,1), activation='relu')
layer3.compile(optimizer='adam')

# make output
output = Output((1,1), (1,1), np.array([[0.34]]), 'sigmoid', '')

for i in range(2000):
     conv_out = convLayer3.forward(poolingLayer.forward(convLayer2.forward(convLayer1.forward(input))))
     final_out = output.forward(layer3.forward(layer2.forward(flattenLayer.forward(conv_out))))
     print(final_out)
     # train fully-connected portion
     fully_connected_backprop = layer2.backward(layer3.backward(output.backward(final_out)))
     # train convolutional portion:
     convLayer1.backward(convLayer2.backward(poolingLayer.backward(convLayer3.backward(flattenLayer.backward(fully_connected_backprop)))))
     

#layer3.forward(layer2.forward(flattenLayer.forward(convLayer.forward(input))))






[[0.50664437]]
[[0.50664432]]
[[0.50664427]]
[[0.50664422]]
[[0.50664416]]
[[0.50664411]]
[[0.50664406]]
[[0.50664401]]
[[0.50664396]]
[[0.5066439]]
[[0.50664385]]
[[0.5066438]]
[[0.50664375]]
[[0.5066437]]
[[0.50664364]]
[[0.50664359]]
[[0.50664354]]
[[0.50664349]]
[[0.50664344]]
[[0.50664339]]
[[0.50664334]]
[[0.50664328]]
[[0.50664323]]
[[0.50664318]]
[[0.50664313]]
[[0.50664308]]
[[0.50664303]]
[[0.50664298]]
[[0.50664293]]
[[0.50664287]]
[[0.50664282]]
[[0.50664277]]
[[0.50664272]]
[[0.50664267]]
[[0.50664262]]
[[0.50664257]]
[[0.50664252]]
[[0.50664247]]
[[0.50664241]]
[[0.50664236]]
[[0.50664231]]
[[0.50664226]]
[[0.50664221]]
[[0.50664216]]
[[0.50664211]]
[[0.50664206]]
[[0.506642]]
[[0.50664195]]
[[0.5066419]]
[[0.50664185]]
[[0.5066418]]
[[0.50664175]]
[[0.50664169]]
[[0.50664164]]
[[0.50664159]]
[[0.50664154]]
[[0.50664149]]
[[0.50664143]]
[[0.50664138]]
[[0.50664133]]
[[0.50664128]]
[[0.50664123]]
[[0.50664117]]
[[0.50664112]]
[[0.50664107]]
[[0.50664102]]
[[0.50664096]]
[[

## multiple channel example of maxpooling backprop

In [3]:
input = np.array([[
    [111,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
],
[
    [30, 31, 32, 33, 34],
    [35, 36, 37, 38, 39],
    [40, 41, 42, 43, 44],
    [45, 4, 44, 488, 49],
    [50, 51, 52, 53, 54]]
])

pool_size = (3,3)
stride = 1
output_size = int((input.shape[1] - pool_size[0])/stride) + 1
output = np.zeros((input.shape[0], output_size, output_size))
positions = np.zeros(output.shape, dtype=(int, 3))
for i in range(output_size): # rows
    for j in range(output_size): # columns
        row_start = i*stride
        row_end = row_start + pool_size[0]
        col_start = j*stride
        col_end = col_start + pool_size[1]
        for k in range(input.shape[0]): # channels
            frame = input[k,row_start:row_end, col_start:col_end]
            output[k,i,j] = np.max(frame)
            # get the spot in the frame with the max value
            positions[k,i,j,1:] = np.unravel_index(np.argmax(frame), frame.shape)
            # add channel to position
            positions[k,i,j,0] = k
            # add offsets to get the spot in the output matrix with max value of this frame
            positions[k,i,j,1] += row_start
            positions[k,i,j,2] += col_start
            
output_grads = np.array(
    [
        [
            [1, 2, 3],
            [4,5,6],
            [7,8,9]
        ],

        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
    ]
)
r_val = np.zeros(input.shape)
channel_pos = positions[:, :, :, 0]
row_pos = positions[:, :, :, 1]
col_pos = positions[:, :, :, 2]
r_val[channel_pos, row_pos, col_pos] = output_grads
print(input)
print(output)
print(r_val)


[[[111   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45   4  44 488  49]
  [ 50  51  52  53  54]]]
[[[111.  14.  15.]
  [ 18.  19.  20.]
  [ 23.  24.  25.]]

 [[ 42.  43.  44.]
  [ 45. 488. 488.]
  [ 52. 488. 488.]]]
[[[ 1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  2.  3.]
  [ 0.  0.  4.  5.  6.]
  [ 0.  0.  7.  8.  9.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0. 10. 11. 12.]
  [13.  0.  0. 18.  0.]
  [ 0.  0. 16.  0.  0.]]]


In [6]:
output_grads.reshape((18,1))
output_grads

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])