In [1]:
import numpy as np

w = np.array([
    [0.1, 0.4],
    [0.8, 0.6]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.00265], [-0.00817]])
output = np.array([[0.35], [0.9]])
activation[1](output) * (w @ grad_output)

array([[-0.00080376],
       [-0.00063198]])

In [2]:
w = np.array([
    [0.3],
    [0.9]
])
sig = lambda x: 1/(1+np.exp(-x))
activation = [sig, lambda x:  x*(1-x)]
grad_output = np.array([[-0.0407]])
output = np.array([[0.680], [0.664]])
activation[1](output) * (w @ grad_output)

array([[-0.0026569],
       [-0.0081723]])

In [1]:
from model.layers.dense import Dense
from model.layers.output import Output
from model.layers.input import Input
import numpy as np


layer1 = Input((2,0), (2,0), 2, np.array([[0.1,0.4], [0.8,0.6]]))
layer2 = Dense((2,0), (1,0), 2, np.array([[0.3], [0.9]]))
layer3 = Output((1,0), (1,0), np.array([[0.5]]), 'sigmoid', '')

input = np.array([[0.35,0.9]]).T
sig = lambda x: 1/(1+np.exp(-x))
for i in range(50):
    final_out = layer3.forward(layer2.forward(layer1.forward(input)))
    print(final_out)
    layer1.backward(layer2.backward(layer3.backward(final_out)))



[[0.69028349]]
[[0.27232597]
 [0.87299836]]
[[0.09844283 0.39844283]
 [0.79419037 0.59419037]]
[[-0.04068113]]
[[-0.00265449]
 [-0.00817165]]
